# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 12:14
from __future__ import unicode_literals

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('slug', models.CharField(blank=True, db_index=True, max_length=256, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=1024, verbose_name='Description')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Published')),
                ('published', models.NullBooleanField(verbose_name='Is published')),
                ('deleted', models.NullBooleanField(verbose_name='Is deleted')),
                ('author_name', models.CharField(blank=True, max_length=256, verbose_name='Author name')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='Is read')),
                ('notified', models.NullBooleanField(verbose_name='Is notified')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=blog.models.get_avatar_path, verbose_name='Custom Image')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone number')),
                ('skype', models.CharField(blank=True, max_length=128, null=True, verbose_name='Skype nick')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.CustomImage', verbose_name='User avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('sended', models.NullBooleanField(verbose_name='Is sent')),
                ('status', models.SmallIntegerField(default=1, verbose_name='Sending status')),
                ('to_addr', models.EmailField(max_length=254, verbose_name='Subscriber email address')),
                ('sending_date', models.DateTimeField(blank=True, null=True, verbose_name='Date of sending')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('subject', models.CharField(max_length=128, verbose_name='Subject')),
                ('from_addr', models.EmailField(blank=True, max_length=254, verbose_name='Sender email address')),
                ('message', models.TextField(blank=True, verbose_name='Body')),
                ('slug', models.SlugField(help_text='Unique slug for internal usages.', unique=True, verbose_name='Slug')),
                ('num_of_retries', models.PositiveIntegerField(default=0, verbose_name='Number of retries')),
                ('interval', models.PositiveIntegerField(blank=True, help_text='Specify sending interval in the seconds.', null=True, verbose_name='Send interval')),
                ('default', models.BooleanField(default=False, verbose_name='Is default template')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Mail template',
                'verbose_name_plural': 'Mail templates',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blog.CustomUser', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='blog',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, to='blog.CustomUser', verbose_name='Subscribed users'),
        ),
        migrations.AddField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
